name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Unzip archive
        run: |
          mkdir -p extract
          unzip slovlendd.zip -d extract/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: y4bFHq-s2UBa8137FJSsvYRI_2t1az9YTwIXYr3v
          accountId: 15ce330f12a14defba3f9ce7b3088157
          command: pages deploy --project-name=mynewsitefortest extract/

      - name: Cleanup Repository
        run: |
          find . -maxdepth 1 ! -name '.github' ! -name '.git' ! -name '.' ! -name '..' ! -name 'slovlendd.zip' -exec rm -rf {} \;
          rm -f slovlendd.zip
          
          rm -f .github/workflows/action.yml
          
          
          # Настройка Git
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          # Добавление изменений
          git add -A
          # Проверка на наличие изменений и коммит
          git diff --staged --quiet || git commit -m "Cleanup repository"
          # Пуш изменений
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
