name: Deploy to Cloudflare Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Unzip archive
        run: |
          mkdir -p extract
          unzip basiron.zip -d extract/

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: qYJqiTQsxmzYoAqTto4rQJu_wBbw2LL3lbpmvVJ8
          accountId: 1e36ccce96a06c39b50d6d87c6ca6782
          command: pages deploy --project-name=bastilions extract/

      - name: Cleanup Repository
        run: |
          find . -maxdepth 1 ! -name '.github' ! -name '.git' ! -name '.' ! -name '..' ! -name 'basiron.zip' -exec rm -rf {} \;
          rm -f basiron.zip
          
          rm -f .github/workflows/action.yml
          
          
          # Настройка Git
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          # Добавление изменений
          git add -A
          # Проверка на наличие изменений и коммит
          git diff --staged --quiet || git commit -m "Cleanup repository"
          # Пуш изменений
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
